<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-U658RUAI" failures="5" tests="5" name="Test" time="0.084" errors="0" timestamp="2021-02-25T13:28:00 CST">
  <testcase classname="NewTestForRenPactice" name="test_case_003" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at NewTestForRenPactice.test_case_003(NewTestForRenPactice.java:10)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test_case_003 -->
  <testcase classname="NewTestAPI" name="test_case_001" time="0.001">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at NewTestAPI.test_case_001(NewTestAPI.java:18)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test_case_001 -->
  <testcase classname="NewTestAPI" name="test_case_001" time="0.005">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at NewTestAPI.test_case_001(NewTestAPI.java:18)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test_case_001 -->
  <testcase classname="NewTestAPI" name="test_case_001" time="0.006">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at NewTestAPI.test_case_001(NewTestAPI.java:18)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test_case_001 -->
  <testcase classname="NewTestAPI" name="test_case_002" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [123] but found [1235]">
      <![CDATA[java.lang.AssertionError: expected [123] but found [1235]
at NewTestAPI.test_case_002(NewTestAPI.java:31)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- test_case_002 -->
  <testcase classname="NewTestAPI" name="beforeMethod" time="0.0">
    <ignored/>
  </testcase> <!-- beforeMethod -->
</testsuite> <!-- Test -->
